version: '3'

services:
  db_mysql:
    container_name: mysql.local
    image: mysql/mysql-server:8.0.28
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'exposed_study'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3307'
    volumes:
      - './volumes/mysql/default:/var/lib/mysql'
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
      - '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'